--- #YAML:1.0
name:               moviecap
version:            1.02
abstract:           get a screenshots within a movie file
author:
    - Leo Charre leocharre at cpan dot org
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Getopt::Std::Strict:  1.01
    LEOCHARRE::Basename:  0
    LEOCHARRE::Dir:       0
    Test::Simple:         0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
